repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
      - id: ruff-format
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.96.1
    hooks:
      - id: terraform_providers_lock
        args:
          - --args=-platform=linux_amd64
          - --tf-init-args=-upgrade
        fail_fast: false
      - id: terraform_fmt
        fail_fast: false
      - id: terraform_docs
        args:
            - --hook-config=--path-to-file=README.md
            - --hook-config=--add-to-existing-file=true
            - --hook-config=--create-file-if-not-exist=true
            - --hook-config=--use-standard-markers=true
        fail_fast: false

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.96.1
    hooks:
      - id: terraform_tflint
        args:
          - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
        fail_fast: true
      - id: terraform_validate
        fail_fast: true
